apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: whoami

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: whoami
spec:
  host: whoami.apps.hens.cluster.chp4.io
  to:
    kind: Service
    name: whoami
  port:
    targetPort: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: tsterk/whoami
          ports:
            - name: web
              containerPort: 8080
